### ISSUE TITLE
Maxgui does not compile on Windows 10

### ISSUE THREAD

**Issue by bornd37** [bmx-ng/maxgui.mod#10]
Using Mingw 7.1.0 i686. Brl.mod and pub.mod compile. By changing the following lines I can get maxgui to compile:

line 2867:
old - MemCopy tmpTipOutput, tmpBufferMem, (tmpTipString.length+1) * 2
new - MemCopy tmpTipOutput, tmpBufferMem, Size_T((tmpTipString.length+1) * 2)

line 4267:
old - bstr=SysAllocStringLen(tmpWString,Text.length);MemFree tmpWString
new - bstr=SysAllocStringLen(tmpWString,UInt(Text.length));MemFree tmpWString

**Comment by woollybah** [comment]
This works now.
