### ISSUE TITLE
PopupWindowMenu

### ISSUE THREAD

**Issue by thareh** [bmx-ng/maxgui.mod#12]
Seems like PopupWindowMenu creates duplicates in the Window menu bar for some reason on Windows, I included a code file with an example.
[PopupWindowMenu.txt](https://github.com/bmx-ng/maxgui.mod/files/1832593/PopupWindowMenu.txt)

**Comment by woollybah** [comment]
So it does.

I tested it with the legacy compiler and it happens there too - for a change it doesn't appear to be a feature I've introduced.
