### ISSUE TITLE
Suggested change in Maxgui/maxgui.mod

### ISSUE THREAD

**Issue by degac** [bmx-ng/maxgui.mod#2]
To change - with one single commands - all the font's gadget in a window/panel

Function SetGadgetFont( gadget:TGadget,font:TGuiFont )
	gadget.SetFont( font )
 	If GadgetClass(gadget)=GADGET_WINDOW Or GadgetClass(gadget)=GADGET_PANEL
		For Local gk:Tgadget=EachIn gadget.kids
			if gk SetGadgetFont(gk,font)		
		Next
	End If
 End Function

**Comment by woollybah** [comment]
I made it optional, by adding a parameter ```applyToChildren``` which defaults to False.
