### ISSUE TITLE
The joy of different linux distributions, or not?

### ISSUE THREAD

**Issue by olejr** [bmx-ng/maxgui.mod#22]
Trying to get NG/maxgui.mod to work on OpenSuse Leap 15 x64 was "fun".

First of.. I downloaded latest release (BlitzMax Linux.x64 v0.98.3.27)
MaxIDE won't run, bummer. Unable to find _libwebkit-3.0_ it says...

Searching through the official packages for opensuse gives nothing of that kind..
Only thing remotely similar is  libwebkit2gtk-4.0 which I think is for gkt2(?). Doesn't work either way.

But google tells me there's an [repository](https://software.opensuse.org/package/libwebkitgtk-3_0-0) that has a version marked as 2.4.11: "installs that one", IDE runs yey!

Now to rebuild modules.. (and adding the right devel packages).
Removed mky.mod and sdl.mod to make it easier/faster to compile, and find missing devel packages.
Quiet easy to get pub & brl buildig, but maxgui.mod not so..
Turns out that opensuse doesn't use _/usr/lib/glib-2.0/include_ but _/usr/lib64/glib-2.0/include_.
So had to add that to (atleast) gtk3maxgui.bmx and maxguitextareascintilla.bmx ,
last one also needed _/usr/include/wayland_ to compile.

So that's why I post this here, as a maxgui.mod "issue". It was the one that needed some editing to work.

Anyway this is only kind of  a "heads up"/rant from me trying bmx-ng on something different than debian/ubuntu.

**Comment by woollybah** [comment]
10 points for effort :-)

Supporting "other" distros is a bit of an edge-case, since the likely number of users that may use them is perhaps in the low single-digits.
But I'm happy to add extra Imports/docs/code-tweaks as required to make it easier for those few to be able to run it on their desired platforms.

A PR would be nice, if you are up for it, or a detailed list of the changes you made - if there's more than mentioned above.
Otherwise, it'll be a little longer until I get the time to try it myself.

There's still tons of docs to write for the website too... ho hum...

**Comment by olejr** [comment]
Will look into the PR thingy. Or atleast do a detailed list of what-to-do-where..

The idea was to try to do the same thing with other, not debian based distros, ie fedora/centos/manjaro..

**Comment by woollybah** [comment]
I've recently added a maxgui.gtk3webkit2gtk which resolves the issue you were having trying to get the old one working in openSUSE.
I've been trying out a few distros to see what needs to be fixed/documented to get stuff working.
* openSUSE Tumbleweed (with xcfe) works very well. MaxIDE runs fine. Digesteroids (on SDL) runs great.
* Fedora (30), not so much - well, MaxGUI is a bit of a mess to say the least, but MaxIDE is mostly useable. Digesteroids (on SDL) runs great though, so not all is lots ;-)

I'd probably expect centos to be very similar to Fedora...

**Comment by olejr** [comment]
Great!
As of Fedora "not working" it's kind of "bleeding edge"/testbed RedHat as far as I know.
And CentOS is like RedHat enterprise without the cost, 
older more stable(?) packages than Fedora because of, well, enterprise stuff..
Will, when time permits test it on CentOS, too much "life" going on at the moment.

Anyway, closing this as my goto distro, OpenSuse, is now working.
