### ISSUE TITLE
CreateCanvas returns Null object on latest linux (ubuntu)

### ISSUE THREAD

**Issue by markcwm** [bmx-ng/maxgui.mod#28]
Hi,

I've NG (v0.99-3.31) installed on a 32-bit ubuntu 18.04 (bionic) and Maxgui.Gtk3maxgui examples are working but I noticed a problem. Try testing maxgui.mod/maxgui.mod/doc/createcanvas.bmx it should report 'Unhandled exception: Attempt to access field or method of Null object'.

I've tried using the old Bah.Gtkmaxgui but I can't get it to run, it just says 'identifier Driver not found'. I use Gtk1 on my older ubuntu 16.04 install with no problems, I don't think I've tried using Gtk3 there so I'll get back to you on that.

**Comment by markcwm** [comment]
Ah yes, it doesn't build on 16.04 ubuntu. I get:

Compile Error: Identifier 'systemdriver' not found.
[~/bmx-ng/mod/gtk.mod/gtk3maxgui.mod/gtkgadget.bmx;4007;0]

I checked for dependencies with 'dpkg -L libgtk-3-0' and libgtk-3-dev and they're installed.

**Comment by GWRon** [comment]
Dunno if this is the same but with NG maxgui.bmx's code:
```blitzmax
Function CreateCanvas:TGadget( x,y,w,h,group:TGadget,style=0 )
	Local t:TGadget=maxgui_driver.CreateGadget(GADGET_CANVAS,"",x,y,w,h,GetGroup(group),style)
	Assert t, "maxgui_driver.CreateGadget failed" 'added by me
	t.AttachGraphics DefaultGraphicsFlags()	'gfxFlags
	Return t
End Function
```
asserts that canvas wasn't created too. With vanilla it works. Also on Windows the very same code works.
The code uses "Brl.Timer" and "Brl.GLMax2D", so no SDL.

**Comment by GWRon** [comment]
gtk3maxgui.mod/gtkgadget.bmx contains a TGTKCanvas which is commented out - also other occourences of TGTKCanvas are rem'd.

Might explain why this does not work yet.

**Comment by GWRon** [comment]
Open maxgui.mod/gtk3maxgui.mod/gtkcommon.bmx and add to the "extern" part:
```
	Function gdk_x11_window_get_xid:Byte Ptr(handle:Byte Ptr)
```

Open gtkgadget.bmx in the same folder and replace the function:
```BlitzMax
	Method CanvasGraphics:TGraphics()
		If Not canvas Then
			canvas = BRL.Graphics.AttachGraphics(gdk_x11_window_get_xid(gtk_widget_get_window(handle)), Mode)
		End If

		Return canvas
	End Method
```
(it replaces "gdk_x11_drawable_get_xid" with the corresponding gtk3 function "gdk_x11_window_get_xid" (they BOTH rely on the existence of X11 - so wayland-using distributions are out).

In the "Method initCanvas" of the very same file I replaced the event connections:
```
		addConnection("button-press-event", g_signal_cb3_ret(handle, "button-press-event", OnMouseDown, Self, Destroy, 0))
		addConnection("button-release-event", g_signal_cb3_ret(handle, "button-release-event", OnMouseUp, Self, Destroy, 0))
		addConnection("enter-notify-event", g_signal_cb3_ret(handle, "enter-notify-event", OnMouseEnter, Self, Destroy, 0))
		addConnection("leave-notify-event", g_signal_cb3_ret(handle, "leave-notify-event", OnMouseLeave, Self, Destroy, 0))
		addConnection("motion-notify-event", g_signal_cb3_ret(handle, "motion-notify-event", OnMouseMove, Self, Destroy, 0))
		addConnection("scroll-event", g_signal_cb3(handle, "scroll-event", OnScroll, Self, Destroy, 0))

		addConnection("key-press-event", g_signal_cb3_ret(handle, "key-press-event", OnKeyDown, Self, Destroy, 0))
		addConnection("key-release-event", g_signal_cb3_ret(handle, "key-release-event", OnKeyUp, Self, Destroy, 0))
```

It now compiled properly - but the canvas kept empty (and contained a scrollbar for me - once scrolled the canvas went black, so it did not work as expected). 


Maybe that still helps.

**Comment by GWRon** [comment]
I manually added a new "addConnection" to react to "draw" events.
Result was a black-canvas wit white arrows - a bit flickering.

```BlitzMax
...
		addConnection("draw", g_signal_cb3_ret(handle, "draw", OnDraw, Self, Destroy, 0))
...


	Function OnDraw:Int(widget:Byte Ptr, cairo:Byte Ptr, obj:Object)
		PostGuiEvent(EVENT_GADGETPAINT, TGadget(obj))
	End Function

```

Maybe we need to implement GtkDrawingArea?
https://developer.gnome.org/gtk3/stable/GtkDrawingArea.html

**Comment by GWRon** [comment]
Sorry for spamming ;-)

I added `SetClsColor 255,255,255` in the createcanvas.bmx before doing the `cls`. The result was an alternating display of full-black or full-white (as the arrows there white too). It looks as if only every second frame was "drawn".

**Comment by markcwm** [comment]
Thanks for the help Ron, definitely not spam. :)

Well, I tried your code but I just can't get it to run, I keep getting the 'Null object' error from CreateGadget in Maxgui.Maxgui. 

I did notice the error 'identifier Driver not found' means the module just isn't built/defined.

**Comment by Hezkore** [comment]
A real shame this isn't fixed yet.

**Comment by GWRon** [comment]
Did above - but replaced the "draw"-event connection as I mistakingly used `g_signal_cb3_ret` but as CanvasRedraw does not return anything it has to be `g_signal_cb3`. So this step should only be then:
```
		'Ronny: in GTK3 this is "draw"
		'addConnection("expose_event", g_signal_cb3(handle, "expose_event", CanvasRedraw, Self, Destroy, 0))
		addConnection("draw", g_signal_cb3(handle, "draw", CanvasRedraw, Self, Destroy, 0))
```

result is still this:

![canvas](https://user-images.githubusercontent.com/2625226/128647310-8ac7a7a0-ada8-4aea-b3b2-dfbfe7519577.gif)

**Comment by Hezkore** [comment]
Having applied the diff file; I can confirm that it works.
Well done @GWRon

**Comment by GWRon** [comment]
@markcwm 
why do you close it ? The PR is not merged - so the issue should still be open.

**Comment by markcwm** [comment]
OK, sorry, just that I consider this done.
