### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/maxgui.mod#3]
Hiya,

After updating all mods this evening I'm getting build errors in this one

    [ 99%] Processing:win32maxguiex.bmx
    Compile Error: Module does not match commandline module
    [C:/BlitzMaxNG/mod/maxgui.mod/win32maxguiex.mod/win32maxguiex.bmx;6;0]
    Build Error: failed to compile (-1) C:/BlitzMaxNG/mod/maxgui.mod/win32maxguiex.mod/win32maxguiex.bmx
    Process complete

Or I get a duplicate error...

    Compile Error: Duplicate identifier 'getclassnamew' found in module 'maxgui_win32maxguiex_common' and module 'pub.win32'.

**Comment by woollybah** [comment]
Sorry. should be okay now.
