### ISSUE TITLE
GTK/Scintilla on Windows - no "Alt Gr"+numbers symbols

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/maxgui.mod#31]
Somewhere @woollybah stated that the gtk/scintilla implementation seems to work well on windows.

I thought so too - until I needed square brackets (`arr[ ]`). On German keyboard layouts you need to press "alt gr" + "8" (or "9"). All these combinations (1,2,3...) do not work. 
So you are not able to use the backslash too ("alt gr" + the key next to 9 - here the key of "ß").

**Comment by woollybah** [comment]
This is an excellent tool : https://w3c.github.io/uievents/tools/key-event-viewer.html

**Comment by woollybah** [comment]
Did the commit fix your issue?

**Comment by GWRon** [comment]
Was not able to test it yet (will do at home) but I had the change lines also in focus...so I assume it should ;-)

Will report later.

**Comment by GWRon** [comment]
Scrub above's comment - I booted up a Linux Box (Mint 19) and it worked ... checked commit timestamp and NG-release-timestamp, wondered, booted Windows to answer here ... and saw that I was talking about a Windows issue :-)

Yes... Windows version works properly now (Alt Gr, Caret Line, ...).
