### ISSUE TITLE
[MaxGUITextAreaScintilla.mod] Behaviour differs

### ISSUE THREAD

**Issue by thareh** [bmx-ng/maxgui.mod#36]
Hi!

I'm using some custom code in my MaxIDE and after the switch to Scintilla it isn't working properly any more, and I think it's due to the behaviour of TextAreaSelLen with TEXTAREA_LINES not being true to the original TextArea behaviour.

When I have 2 full lines selected it returns only 1 where it returned 2 before.

Also, there might be a similar issue with SelectTextAreaText using TEXTAREA_LINES, in Scintilla the cursor ends up at a different position than the original TextArea counterpart.

**Comment by GWRon** [comment]
What do you mean with "two full lines"... Including the last line break (so cursor on first position of the third line) or not?

Think this something scintilla devs might interpret differently.

**Comment by thareh** [comment]
Cursor not on the third line but anywhere on the second line would return 2 on the original TextArea I believe :)

**Comment by woollybah** [comment]
It would be appreciated if you could provide a (very) minimal example of the issue you are seeing.

Thanks :-)

**Comment by woollybah** [comment]
Until we get the problem resolved, you can just switch back to using the standard text area by commenting out the line that specifically imports the new one.

**Comment by GWRon** [comment]
The issue is in glue.c

`int bmx_mgta_scintilla_getselectionlength(SCI_HANDLE sci, int units)`

For lines it should add "+1" to result in what @thareh expects.
So with only a single char selected it should return "0+1".

Another option would be a character-based counter. Fetch the selection and count line breaks. That way a single char would return 0 while a selection over (parts of) two lines leads to 1

**Comment by GWRon** [comment]
Now  check win32maxguiex.mod/win32maxguiex.bmd

`Method GetSelectionLength(units)`

It also adds +1.

Also it subtracts 1 from the end selection cursor position...so a selection ending at the very first position of a new line leads to a line count of x-1.

This is also not taken into consideration in the scintilla implementation

**Comment by GWRon** [comment]
Without checking it now it seems as if the gtk implementation differs to the win32 implementation already as it does the same as scintilla does: subtracting line of "selection start" from "selection end".

@thareh 
I assume you use MaxIDE on Windows?

**Comment by GWRon** [comment]
Macos is not affected as the `int NSGetSelectionlength(nsgadget *gadget, on units)` function in cocoa.macos.m already handles it the way the win32maxguiex.mod implementation does.


Think the little bug was introduced by @woollybah when creating the gtk wrapper...and then got reused when he wrote the scintilla code

**Comment by thareh** [comment]
Yes, I am indeed using Windows.

I can provide an example a bit later if need be! :)
