### ISSUE TITLE
Support webkit2gtk

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/maxgui.mod#37]
webkit2gtk became a thing in 2013, and some current versions of Linux (e.g. Fedora 30) no longer provide webkitgtk.
We should either add a new gtk3webkit2gtk.mod, or migrate the current one to use webkit2gtk instead - changes to api, etc.

On the assumption that most distros are now shipping with webkit2gtk, we may as well migrate the current module.

**Comment by GWRon** [comment]
Keep the old for sake of old distribution compatibility?
But use the new one in projects shipped with NG as default.

**Comment by woollybah** [comment]
Added a new module :-)
