### ISSUE TITLE
Compile Error: maxgui.gtk3maxgui.mod

### ISSUE THREAD

**Issue by xlsior75** [bmx-ng/maxgui.mod#39]
Same as the cocoamaxgui.mod yesterday,  gtk3maxgui.mod is also missing the 'strict' definition and won't compile:  Latest BCC/BMK, Windows (x86,x64, release, debug)

**Comment by GWRon** [comment]
It is not necessarily missing. The latest bcc requires `strict` or `superstrict` but only accepts them right on top. Legacy and older bcc NG accepted later (after `moduleinfo`.
