### ISSUE TITLE
[Win32] Listbox creates unnecessary horizontal scrollbar

### ISSUE THREAD

**Issue by thareh** [bmx-ng/maxgui.mod#45]
Hi,

If you add items to a listbox until the vertical scrollbar appears, the horizontal scrollbar also appears even though it's not needed. (due to the vertical scrollbar taking up space I'd guess)

```
Framework BRL.Blitz
Import MaxGUI.Drivers
Import BRL.EventQueue

Local Window:TGadget = CreateWindow("Test", 0, 0, 640, 480, Null, WINDOW_TITLEBAR | WINDOW_CENTER | WINDOW_CLIENTCOORDS | WINDOW_RESIZABLE)

Local List:TGadget = CreateListBox(20, 20, ClientWidth(Window)-40, ClientHeight(Window)-40, Window)

For Local I:Int = 0 To 25
	AddGadgetItem(List, "testing")
Next

Repeat
	
	WaitEvent()
	
	Select EventID()
		Case EVENT_WINDOWCLOSE
			End
	EndSelect
	
Forever
```

Thanks,
-- Thareh

**Comment by GWRon** [comment]
In my GUI (graphics engine based not OS) i checked this twice or did additional checks to avoid this scrollbars appearing because another scrollbar would be affed too.

**Comment by thareh** [comment]
Would adding `SendMessageW _hwnd,LVM_SETCOLUMNWIDTH,0,LVSCW_AUTOSIZE_USEHEADER` to the end of the method `InsertListItem` for the class `TWindowsListBox` be a proper fix?

**Comment by GWRon** [comment]
Well done @thareh
