### ISSUE TITLE
maxgui.bmx: Unable to convert from 'Int' to 'Byte Ptr'

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/maxgui.mod#5]
Seems `owner` is of a different type now (int)

`Function SetHotKeyEvent:THotKey( key,mods,event:TEvent=Null,owner:Byte Ptr=0 )`

**Comment by woollybah** [comment]
Fixed.

**Comment by GWRon** [comment]
I get that very same error with "maxmods/brl.mod and pub.mod + maxgui.mod". Any chances for a "maxgui.mod" stored in maxmods and updated to work with brl/pub.mod ?
