### ISSUE TITLE
DefaultGraphicsFlags() is "long" - AttachGraphics() expects "int"

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/maxgui.mod#59]
Brl.mod/graphics.mod/graphics.bmx defines:
`Function DefaultGraphicsFlags:Long()`

But maxgui's backends define "AttachGraphics()" this way:
`Method AttachGraphics:TGraphics( flags )`
or
`Method AttachGraphics:TGraphics( flags:Int )`

so either cast in the only usage of DefaultGragraphicsFlags() in maxgui.mod/maxgui.mod/maxgui.bmx:
`t.AttachGraphics int(DefaultGraphicsFlags())	'gfxFlags`

or make all AttachGraphics accept a `long`.

**Comment by markcwm** [comment]
I vote for defining it as an int DefaultGraphicsFlags:Int() as Flags only needs to be 32 bits.

**Comment by markcwm** [comment]
> It is defined as long for a reason (within sdl it contains more flags...). But am not sure if you can simply cast to an int and ignore the sdl stuff.
Oh right I don't use SDL, so yes it would have to be long for SDL with maybe casting to int for GL/D3D drivers. In 0.129 it looks like AttachGraphics flags is mostly undefined.

**Comment by GWRon** [comment]
Ahh my bad ... I was still on a local "fix" branch which was not updated to the "december commits". Sorry.
