### ISSUE TITLE
Some errors about functions (Byte Ptr redefinition)

### ISSUE THREAD

**Issue by eagle54** [bmx-ng/maxgui.mod#6]
see https://github.com/bmx-ng/bcc/issues/214
see https://github.com/bmx-ng/sdl.mod/issues/9

It's not possible to build maxgui mod without Byte Ptr redefinition, see :

`ReleaseDC`
`SendMessageW`
`CreateWindowExW`
and others ...

You should add Byte Ptr(...) for args inside func. (see code inside win32maxguiex.bmx)

**Comment by woollybah** [comment]
Fixed
