### ISSUE TITLE
Errors compiling MaxGUI programs with x86

### ISSUE THREAD

**Issue by noroads2015** [bmx-ng/maxgui.mod#7]
Compiling this program with Architecture set to x86 
```
SuperStrict
Import maxgui.drivers

Global Window:TGadget = CreateWindow("test",10,10,640,400)
Repeat
	WaitEvent()
	If EventID() = EVENT_APPTERMINATE Or EventID() = EVENT_WINDOWCLOSE Then End
Forever

```
Produces these errors

> C:/BlitzMaxNG/mod/maxgui.mod/win32maxguiex.mod/win32maxguiex.debug.win32.x86.a(win32maxguiex.bmx.debug.win32.x86.o): In function `maxgui_win32maxguiex_TWindowsGUIDriver_GetThemeHandle_pb_pbS':
> C:/BlitzMaxNG/mod/maxgui.mod/win32maxguiex.mod/.bmx/win32maxguiex.bmx.debug.win32.x86.c:3765: undefined reference to `OpenThemeData'
> C:/BlitzMaxNG/mod/maxgui.mod/win32maxguiex.mod/win32maxguiex.debug.win32.x86.a(win32maxguiex.bmx.debug.win32.x86.o): In function `maxgui_win32maxguiex_TWindowsGUIDriver_CloseThemeHandle_i_pb':
> C:/BlitzMaxNG/mod/maxgui.mod/win32maxguiex.mod/.bmx/win32maxguiex.bmx.debug.win32.x86.c:3792: undefined reference to `CloseThemeData'
> C:/BlitzMaxNG/mod/maxgui.mod/win32maxguiex.mod/win32maxguiex.debug.win32.x86.a(win32maxguiex.bmx.debug.win32.x86.o): In function `maxgui_win32maxguiex_TWindowsGadget_DrawParentBackground_pb_pbpbi':
> C:/BlitzMaxNG/mod/maxgui.mod/win32maxguiex.mod/.bmx/win32maxguiex.bmx.debug.win32.x86.c:8155: undefined reference to `DrawThemeParentBackground'
> C:/BlitzMaxNG/mod/maxgui.mod/win32maxguiex.mod/win32maxguiex.debug.win32.x86.a(win32maxguiex.bmx.debug.win32.x86.o): In function `maxgui_win32maxguiex_TWindowsButton_SetTextColor_iii':
> C:/BlitzMaxNG/mod/maxgui.mod/win32maxguiex.mod/.bmx/win32maxguiex.bmx.debug.win32.x86.c:18718: undefined reference to `SetWindowTheme'
> C:/BlitzMaxNG/mod/maxgui.mod/win32maxguiex.mod/win32maxguiex.debug.win32.x86.a(win32maxguiex.bmx.debug.win32.x86.o): In function `maxgui_win32maxguiex_TWindowsListBox_UseExplorerTheme':
> C:/BlitzMaxNG/mod/maxgui.mod/win32maxguiex.mod/.bmx/win32maxguiex.bmx.debug.win32.x86.c:27619: undefined reference to `SetWindowTheme'
> C:/BlitzMaxNG/mod/maxgui.mod/win32maxguiex.mod/win32maxguiex.debug.win32.x86.a(win32maxguiex.bmx.debug.win32.x86.o): In function `maxgui_win32maxguiex_TWindowsTreeView_UseExplorerTheme':
> C:/BlitzMaxNG/mod/maxgui.mod/win32maxguiex.mod/.bmx/win32maxguiex.bmx.debug.win32.x86.c:37339: undefined reference to `SetWindowTheme'
> C:/BlitzMaxNG/mod/maxgui.mod/win32maxguiex.mod/win32maxguiex.debug.win32.x86.a(win32maxguiex.bmx.debug.win32.x86.o): In function `maxgui_win32maxguiex_TWindowsButton_OnDrawItem_TDRAWITEMSTRUCT':
> C:/BlitzMaxNG/mod/maxgui.mod/win32maxguiex.mod/.bmx/win32maxguiex.bmx.debug.win32.x86.c:19504: undefined reference to `IsThemeBackgroundPartiallyTransparent'
> C:/BlitzMaxNG/mod/maxgui.mod/win32maxguiex.mod/.bmx/win32maxguiex.bmx.debug.win32.x86.c:19520: undefined reference to `DrawThemeBackground'
> C:/BlitzMaxNG/mod/maxgui.mod/win32maxguiex.mod/.bmx/win32maxguiex.bmx.debug.win32.x86.c:19523: undefined reference to `GetThemeBackgroundContentRect'
> C:/BlitzMaxNG/mod/maxgui.mod/win32maxguiex.mod/.bmx/win32maxguiex.bmx.debug.win32.x86.c:19515: undefined reference to `DrawThemeParentBackground'
> C:/BlitzMaxNG/mod/maxgui.mod/win32maxguiex.mod/win32maxguiex.debug.win32.x86.a(win32maxguiex.bmx.debug.win32.x86.o): In function `maxgui_win32maxguiex_TWindowsGUIDriver_CloseThemeHandle_i_pb':
> C:/BlitzMaxNG/mod/maxgui.mod/win32maxguiex.mod/.bmx/win32maxguiex.bmx.debug.win32.x86.c:3792: undefined reference to `CloseThemeData'
> C:/BlitzMaxNG/mod/maxgui.mod/win32maxguiex.mod/.bmx/win32maxguiex.bmx.debug.win32.x86.c:3792: undefined reference to `CloseThemeData'
> Build Error: Failed to link C:/BlitzMaxNG/tmp/untitled1.debug.exe
> 

Everything works fine when compiled with X64

**Comment by woollybah** [comment]
Should be working now.
