### ISSUE TITLE
CreateMenu() bug with KEY_NUMx hotkeys

### ISSUE THREAD

**Issue by MidimasterSoft** [bmx-ng/maxgui.mod#74]
A user on syntaxbomb has this ISSUE: If You add in MaxGui a hotkey KEY_NUM0 to the CreateMenu(), the app displays wrong "Menu CTRL +1" in the menu, but reacts correct on CTRL+0. I verified this bug on BlitzMax NG. 

complete report here: https://www.syntaxbomb.com/maxgui/createmenu-bug-with-key_numx-hotkeys/?topicseen

Here is a runnable example:
```SuperStrict 
Import MaxGui.Drivers
Const MENU_NULL:Int = 102

Local Window:TGadget   = CreateWindow("My Window",40,40,320,240)
Local Filemenu:TGadget = CreateMenu("&File",0,WindowMenu(window))
CreateMenu "Menu" , MENU_NULL , filemenu , KEY_NUM0 , MODIFIER_COMMAND
UpdateWindowMenu window

While True
    WaitEvent 
    Select EventID()
        Case EVENT_WINDOWCLOSE
            End
        Case EVENT_MENUACTION
            Select EventData()
                Case MENU_NULL
                    Print "Check"
            End Select
    End Select
Wend `

**Comment by GWRon** [comment]
Linux: works
![image](https://github.com/user-attachments/assets/09e0d0b7-9e63-4240-b2fe-5e779732606c)

Windows (Btw this is BlitzMax 1.50 vanilla...)
![image](https://github.com/user-attachments/assets/09949d01-3747-4caa-9ed5-7da558e0abe7)

Windows (NG):
![image](https://github.com/user-attachments/assets/ea745624-ac08-4a6a-814b-aa5c5f8368c3)

So seems to be a OS-specific issue

**Comment by GWRon** [comment]
For Linux it seems to be a kind of default behaviour (of GTK)
It retrieves the value for Num0 and the modifier (ctrl) and handlet is via some gtk-commands:
gtkgadget.bmx -> setAccelEntry -> gtk_accelerator_parse -> gtk_widget_add_accelerator

For windows the bug seems to be there:
win32maxguiex.mod/win32maxguiex.bmx
```
		ElseIf keycode>=KEY_F1 And keycode<=KEY_F12
			m$="F"+(keycode+1-KEY_F1)
		ElseIf keycode>=KEY_NUM0 And keycode<=KEY_NUM9
			m$="Num "+(keycode+1-KEY_NUM0)
```

As you see - it will be the same "offset" for th F-keys too. Removing the "+1" will fix it.

**Comment by GWRon** [comment]
For Linux I think this is a "GTK" issue, not a "maxgui" issue.

tried it in geany and added "strg + numpad 0" for "save as":
![image](https://github.com/user-attachments/assets/4db11a68-ba68-4e28-b1da-262cd67d963f)

but menu displays:
![image](https://github.com/user-attachments/assets/dab20cd8-aef7-49f4-9700-92f9503b0d38)

I assume this is something the gtk-libs should fix. An alternative nobody will do (too much work for this issue) is to derive a new type (in c) from `gtkAccelLabel` and do some custom stuff in there. `gtkAccelLabel` is what is used behind the scenes by `gtkMenuItem` if you set some accels (so...shortcut listeners)
