### ISSUE TITLE
 Maxide crashes with last version BMX-NG

### ISSUE THREAD

**Issue by eagle54** [bmx-ng/maxgui.mod#8]
Maxide crashes with last version BMX-NG

Hi,

I don't understand, when i rebuild bmx-ng (all -> latest bcc, bmk, mods and maxide), maxide (x86) crashes. I have an exception error and this message in console mode : Libpng warning : iCCP: known incorrect sRGB profile

My config :

Win7 x64 BCC 0.89 BMK 3.17 TDM-GCC64 5.1.0 Latest mods

If you can check this problem

Thanks by advance

Eagle54

**Comment by eagle54** [comment]
1/ Some errors BMX-NG found in maxide.bmx and crash the editor -> bmx-ng (bcc) does not support :

L740->If Not pixLogo Then pixLogo = LoadPixmapPNG(**"incbin::bmxlogo.png"**)
L6350->SetPanelColor panel,255,255,255;SetPanelPixmap panel, LoadPixmapPNG(**"incbin::splash.png"**), PANELPIXMAP_FIT2
L6357->SetGadgetPixmap(window, LoadPixmapPNG(**"incbin::window_icon.png"**), GADGETPIXMAP_ICON )
L6376->toolbar=CreateToolBar(**"incbin::toolbar.png"**,0,0,0,0,window )

You must declare const or global value (local not tested) as :

Incbin "bmxlogo.png"
Incbin "toolbar.png"
Incbin "splash.png"

Const bmxlogo_img$ = "incbin::bmxlogo.png"
Const toolbar_img$ = "incbin::toolbar.png"
Const splash_img$ = "incbin::splash.png"
?Linux
Incbin "window_icon.png"
?
Const window_icon_img$ = "incbin::window_icon.png"

L740->If Not pixLogo Then pixLogo = LoadPixmapPNG(**bmxlogo_img**)
L6350->SetPanelColor panel,255,255,255;SetPanelPixmap panel, LoadPixmapPNG(**splash_img**), PANELPIXMAP_FIT2
L6357->SetGadgetPixmap(window, LoadPixmapPNG(**window_icon_img**), GADGETPIXMAP_ICON )
L6376->toolbar=CreateToolBar(**toolbar_img**,0,0,0,0,window )


2/ I found some others errors (crash) as :

L783->SetGadgetLayout abt.hypBlitz, EDGE_ALIGNED, EDGE_ALIGNED, EDGE_CENTERED, EDGE_ALIGNED

Please check these problems (bcc NG problems ???)


Log errors:

Building maxide
[ 99%] Processing:maxide.bmx
[ 99%] Compiling:maxide.bmx.console.debug.win32.x86.c
[100%] Linking:maxide.debug.exe
Executing:maxide.debug.exe
libpng warning: iCCP: known incorrect sRGB profile
Debugger Error:Invalid scope kind

**Comment by woollybah** [comment]
With the latest builds, maxide appears to run okay.

MaxGUI in general seems to be much more stable these days.
